### ISSUE TITLE
Le Plugin ne fonctionne plus avec Jeedom 3.3.18

### ISSUE THREAD

**Issue by XavCH** [coolweb/MystromJeedom#33]
Bonjour coolweb,
J'utilise votre plugin MyStrom avec mon boitier Jeedom. Il marchait parfaitement bien, je l'ai intégré dans plusieurs scénarios, jusqu'à la mise à jour Jeedom 3.3.18 que j'ai faite ce Week-end.
En fait il continue de marcher à l'exception des actions On et Off qui renvoient un message "500 : internal error". Par conséquent, tous mes scénarios se mettent en erreur.
Votre plugin m'est très utile. Auriez-vous l'amabilité de faire un correctif afin de le rendre compatible avec cette nouvelle version de Jeedom ?
Merci beaucoup.
Cordialement,
XavCH

**Comment by djax666** [comment]
Bonjour coolweb,
J'ai le même problème que XavCH avec la version 3.3.24.
D'après loic de https://www.jeedom.com/forum/viewtopic.php?t=42616&start=240#p699480 , il semble manquer une dépendance 

Mon http.error dit:
[Tue May 28 01:50:53.622615 2019] [:error] [pid 1594] [client 192.168.10.248:64664] PHP Fatal error:  Uncaught Error: Call to a member function logDebug() on null in /var/www/html/plugins/mystrom/core/class/mystrom.class.php:780\nStack trace:\n#0 /var/www/html/core/class/cmd.class.php(977): mystromCmd->execute(Array)\n#1 /var/www/html/core/ajax/cmd.ajax.php(74): cmd->execCmd(Array)\n#2 {main}\n  thrown in /var/www/html/plugins/mystrom/core/class/mystrom.class.php on line 780, referer: http://192.168.10.16/index.php?v=d&p=dashboard
[Tue May 28 01:52:27.322291 2019] [:error] [pid 1230] [client 192.168.10.248:64872] PHP Fatal error:  Uncaught Error: Call to a member function logDebug() on null in /var/www/html/plugins/mystrom/core/class/mystrom.class.php:780\nStack trace:\n#0 /var/www/html/core/class/cmd.class.php(977): mystromCmd->execute(Array)\n#1 /var/www/html/core/ajax/cmd.ajax.php(74): cmd->execCmd(Array)\n#2 {main}\n  thrown in /var/www/html/plugins/mystrom/core/class/mystrom.class.php on line 780, referer: http://192.168.10.16/index.php?v=d&p=dashboard
[Tue May 28 01:53:35.424431 2019] [:error] [pid 1230] [client 192.168.10.248:65023] PHP Fatal error:  Uncaught Error: Call to a member function logDebug() on null in /var/www/html/plugins/mystrom/core/class/mystrom.class.php:129\nStack trace:\n#0 /var/www/html/core/class/DB.class.php(202): mystrom->postSave()\n#1 /var/www/html/core/class/eqLogic.class.php(977): DB::save(Object(mystrom), false)\n#2 /var/www/html/core/ajax/eqLogic.ajax.php(343): eqLogic->save()\n#3 {main}\n  thrown in /var/www/html/plugins/mystrom/core/class/mystrom.class.php on line 129, referer: http://192.168.10.16/index.php?v=d&m=mystrom&p=mystrom

Merci d'avance
Cordialement,
djax666

**Comment by Paolodic** [comment]
Bonjour,
ça ne marche pas même en V4.0 de Jeedom.

Message d'erreur (en rouge):

"[MySQL] Error code : 22007 (1366). Incorrect integer value: '' for column `jeedom`.`cmd`.`isVisible` at row 1 : INSERT INTO `cmd` SET `id` = :id, `logicalId` = :logicalId, `generic_type` = :generic_type, `eqType` = :eqType, `name` = :name, `order` = :order, `type` = :type, `subType` = :subType, `eqLogic_id` = :eqLogic_id, `isHistorized` = :isHistorized, `unite` = :unite, `configuration` = :configuration, `template` = :template, `display` = :display, `value` = :value, `isVisible` = :isVisible, `alert` = :alert"

Merci d'avance
Paolo
